#!/usr/bin/env bash
# setup script for macos
# akash vyas

# usage: run in user's home directory

### tooling ###

# terminal
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install alacritty
brew install neofetch
brew install git
brew install tree
brew install wget

# zsh and oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
brew install thefuck
brew install zsh-autosuggestions
brew install zsh-syntax-highlighting

# window management
brew install koekeishiya/formulae/yabai
brew install koekeishiya/formulae/skhd

# programming languages
brew install python
brew install java
brew install rust
brew install ocaml
brew install go

### applications ###

# browser
brew install --cask firefox
brew install --cask google-chrome

# social
brew install --cask discord
brew install --cask slack
brew install --cask zoom

# development
brew install --cask visual-studio-code
brew install --cask typora

# office
brew install --cask microsoft-office

# other
brew install --cask spotify

### files ###

brew install --cask google-drive

### config ###

# dotfiles
git clone git@github.com:akashkvyas/dotfiles.git
mv dotfiles Dotfiles
ln -s ~/Dotfiles/config/macos ~/.config

# wallpaper
osascript -e 'tell application "Finder" to set desktop picture to POSIX file "~/Dotfiles/wallpapers/nighthawks-edward-hopper-hz.jpg"'

# spicetify
brew install spicetify/homebrew-tap/spicetify-cli
mkdir -p ~/.config/spicetify/themes
cd ~/.config/spicetify/themes
git clone --depth=1 https://github.com/spicetify/spicetify-themes.git 
cd ~
spicetify config current_theme Onepunch color_scheme dark
spicetify apply